export enum GearType {
    HEAD = 'HEAD',
    CHEST = 'CHEST',
    ARMS = 'ARMS',
    WAIST = 'WAIST',
    LEGS = 'LEGS',
    WEAPON = 'WEAPON',
}

export enum WeaponType {
    GREATSWORD = 'GREATSWORD',
    LONG_SWORD = 'LONG_SWORD',
    SWORD_AND_SHIELD = 'SWORD_AND_SHIELD',
    DUAL_BLADES = 'DUAL_BLADES',
    HAMMER = 'HAMMER',
    HUNTING_HORN = 'HUNTING_HORN',
    LANCE = 'LANCE',
    GUNLANCE = 'GUNLANCE',
    SWITCH_AXE = 'SWITCH_AXE',
    CHARGE_BLADE = 'CHARGE_BLADE',
    INSECT_GLAIVE = 'INSECT_GLAIVE',
    LIGHT_BOWGUN = 'LIGHT_BOWGUN',
    HEAVY_BOWGUN = 'HEAVY_BOWGUN',
    BOW = 'BOW',
}
